// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABarww4SA5ZkaALM8jqZWoxo4tiiMoIxw',
    appId: '1:732020516241:web:550f4a9f2165967f786630',
    messagingSenderId: '732020516241',
    projectId: 'angular-host-c05fb',
    authDomain: 'angular-host-c05fb.firebaseapp.com',
    databaseURL: 'https://angular-host-c05fb-default-rtdb.firebaseio.com',
    storageBucket: 'angular-host-c05fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEvo0BMm17JZOtZxODSoGfbbPTAYaFkVE',
    appId: '1:732020516241:android:37eb025dd6460a7e786630',
    messagingSenderId: '732020516241',
    projectId: 'angular-host-c05fb',
    databaseURL: 'https://angular-host-c05fb-default-rtdb.firebaseio.com',
    storageBucket: 'angular-host-c05fb.firebasestorage.app',
  );
}
